### ISSUE TITLE
Fix error with removing QR code

### ISSUE THREAD

**Issue by edmoss345** [IDEMSInternational/parenttext-pipeline#83]
@ed.moss345 or @istride I am getting an error when running the mexico pipeline at the step for removing quick replies:

C:\Users\fagio\Documents\GitHub\parenttext-mexico\node_modules\@idems\idems_translation_chatbot\insert\fix_arg_qr_translation.js:197
                        OtherArg[lang][CorrectArgRef] += " " + OtherQR[lang][row].toString()
                                                                                  ^

TypeError: Cannot read property 'toString' of undefined
    at fix_translated_arguments (C:\Users\fagio\Documents\GitHub\parenttext-mexico\node_modules\@idems\idems_translation_chatbot\insert\fix_arg_qr_translation.js:197:83)
    at Object.fix_arg_qr_translation (C:\Users\fagio\Documents\GitHub\parenttext-mexico\node_modules\@idems\idems_translation_chatbot\insert\fix_arg_qr_translation.js:72:111)
    at Object.fix_arg_qr_translation (C:\Users\fagio\Documents\GitHub\parenttext-mexico\node_modules\@idems\idems_translation_chatbot\index.js:51:51)
    at Object.<anonymous> (C:\Users\fagio\Documents\GitHub\parenttext-mexico\node_modules\@idems\idems_translation_chatbot\index.js:25:22)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)
    at internal/main/run_main_module.js:17:47

any idea of what could be the problem here?

**Comment by edmoss345** [comment]
Having looked into this, the error was occurring because some actions had no associated localisations, meaning when trying to fetch the translated QR to do checks we just got an empty array. As far as I know this is a new phenomenon, for other deployments we always had localisations, just if they were missing translations then the text in the localisations would be in English. I'm not sure what has changed with Mexico, but either way I updated the code so that it will just not try and fix any nodes if there is not a translation held in an associated localisation.

@fagiothree my local tests are running based on a file that was previously crashing, but could you do a test on your latest Mexico pipeline

**Comment by fagiothree** [comment]
Getting a new error now:
C:\Users\fagio\Documents\GitHub\parenttext-mexico\node_modules\@idems\idems_translation_chatbot\insert\modify_quick_replies.js:214
            translations[lang] = messages[curr_act.uuid].quick_replies[i];
                                                         ^

TypeError: Cannot read property 'quick_replies' of undefined
    at C:\Users\fagio\Documents\GitHub\parenttext-mexico\node_modules\@idems\idems_translation_chatbot\insert\modify_quick_replies.js:214:58

only for the tags onboarding, menu & module

**Comment by edmoss345** [comment]
ok will look into this one as well, suspect it is also related to a missing localisation but will see

**Comment by edmoss345** [comment]
Have addressed the latest problem in the following PR

https://github.com/IDEMSInternational/idems_translation/pull/63

Again the problem is related to the fact that there are missing localisations, one for us to discuss why this is happening for mexico. Have republished and updated the reference in the mexico repo so @fagiothree could you please try again, hopefully this is the last problem of this kind
